package model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 18 21:50:03 CET 2021
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void insertSelectedRows();
}

